############################################################################
# board/sf32lb58/sf32lb58-nxboot/src/Makefile
#
# Copyright (C) 2026 Yang Hongbo <yang.hongbo@iotpi.xyz>
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(TOPDIR)/Make.defs

CSRCS = sf32lb58_boot_bringup.c board_boot_image.c
CSRCS += sf32lb58_nxboot_init.c

include $(TOPDIR)/boards/Board.mk
