############################################################################
# Contest 2026 team 162 hello app - Makefile
#
# Copyright (C) 2026 Yang Hongbo <yang.hongbo@iotpi.xyz>
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = hello_app
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_000_HELLO_APP)

MAINSRC = hello_app_main.c

include $(APPDIR)/Application.mk
